### ISSUE TITLE
add_recipe_spec not passing

### ISSUE THREAD

**Issue by ghost** [mwinb/RecipeBuilder#5]
The test [add_recipe_spec](https://github.com/mwinb/RecipeBuilder/blob/master/spec/system/add_recipe_spec.rb) is not passing.

I've isolated the area where it's failing, which is within the create method of CreatesRecipe. After doing some debugging I found when CreatesRecipe tries to save the recipe to the db (recipe.save) it fails. In the debugger I get this:

```
   23:   def create
   24:     build
   25:     byebug
=> 26:     result = recipe.save
   27:     @success = result
   28:   end
   29:
   30:   def convert_ingredients_string

(byebug) recipe.save!

*** ActiveRecord::RecordInvalid Exception: Validation failed: Ingredients is invalid, Steps is invalid
```

Looking at the recipe object it appears to be fine, all the attributes set to be validated are present. This is the only test that is currently failing.

```
(byebug) recipe
#<Recipe id: nil, name: "Pancakes", created_at: nil, updated_at: nil>

(byebug) recipe.ingredients
#<ActiveRecord::Associations::CollectionProxy [#<Ingredient id: nil, recipe_id: nil, name: "Flour", amount: 0.0, acquired: false, created_at: nil, updated_at: nil>, #<Ingredient id: nil, recipe_id: nil, name: "Egg", amount: 0.0, acquired: false, created_at: nil, updated_at: nil>]>

(byebug) recipe.steps
#<ActiveRecord::Associations::CollectionProxy [#<Step id: nil, recipe_id: nil, description: "Mix", completed: false, created_at: nil, updated_at: nil>, #<Step id: nil, recipe_id: nil, description: "Make", completed: false, created_at: nil, updated_at: nil>]>
```

**Comment by mwinb** [comment]
Is the develop branch up to date? cause its currently failing 29 of the tests.

**Comment by mwinb** [comment]
Fixed by adding test for CreatesRecipe create method in creates_recipe_spec which led to finding CreatesRecipe line 10 in build method name: name changed to name: @name. Now passes 37/37 tests.
